ALTER TABLE "InvestmentPlan"
ADD COLUMN "dailyAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN "dayAmount" DECIMAL(18,2) NOT NULL DEFAULT 0,
ADD COLUMN "totalAmount" DECIMAL(18,2) NOT NULL DEFAULT 0;